import type { AdapterConfigSchema } from "@paperclipai/adapter-utils";
import { DEFAULT_DIRECT_OPENROUTER_MODEL } from "../index.js";
import { SHELL_POLICY_VISIBLE_WHEN } from "./shell-policy.js";

export function getConfigSchema(): AdapterConfigSchema {
  return {
    fields: [
      { key: "cwd", label: "Working directory", type: "text" },
      { key: "instructionsFilePath", label: "Agent instructions file", type: "text" },
      { key: "model", label: "Model", type: "text", default: DEFAULT_DIRECT_OPENROUTER_MODEL, required: true },
      {
        key: "toolCallingMode",
        label: "Tool calling mode",
        type: "select",
        default: "native",
        options: [
          { value: "native", label: "Native OpenRouter tool calling" },
          { value: "text", label: "Text fallback tool calling" },
        ],
      },
      { key: "maxTurns", label: "Max turns", type: "number", default: 25 },
      {
        key: "shellPolicy",
        label: "Shell policy",
        type: "select",
        default: "dev",
        options: [
          { value: "dev", label: "Dev allowlist (git, pnpm, npm, rg, …)" },
          { value: "ci", label: "CI strict (no push, no python -c)" },
          { value: "custom", label: "Custom allowlist" },
          { value: "disabled", label: "Disabled (file tools only)" },
        ],
        hint: "Preset command allowlist. Use toggles below to refine dev/ci presets.",
      },
      {
        key: "allowedShellCommands",
        label: "Custom shell allowlist",
        type: "textarea",
        hint: "Comma or newline separated base command names when shellPolicy=custom (e.g. make, cargo).",
        meta: { visibleWhen: { key: "shellPolicy", values: ["custom"] } },
      },
      {
        key: "blockedShellCommands",
        label: "Extra blocked patterns",
        type: "textarea",
        hint: "Optional substrings to always reject in run_shell (e.g. docker, kubectl).",
        meta: { visibleWhen: SHELL_POLICY_VISIBLE_WHEN },
      },
      {
        key: "allowNetworkShellCommands",
        label: "Allow network tools",
        type: "toggle",
        default: false,
        hint: "Permit curl, wget, ssh, scp, rsync, and similar commands when allowlisted.",
        meta: { visibleWhen: SHELL_POLICY_VISIBLE_WHEN },
      },
      {
        key: "allowGit",
        label: "Allow git",
        type: "toggle",
        default: true,
        hint: "When off, git is removed from the dev/ci allowlist.",
        meta: { visibleWhen: { key: "shellPolicy", values: ["dev", "ci"] } },
      },
      {
        key: "allowPackageManagers",
        label: "Allow package managers",
        type: "toggle",
        default: true,
        hint: "When off, node/npm/pnpm/npx/corepack are removed from the dev/ci allowlist.",
        meta: { visibleWhen: { key: "shellPolicy", values: ["dev", "ci"] } },
      },
      {
        key: "allowPython",
        label: "Allow Python",
        type: "toggle",
        default: true,
        hint: "When off, python/python3/pytest are removed from the dev/ci allowlist.",
        meta: { visibleWhen: { key: "shellPolicy", values: ["dev", "ci"] } },
      },
      {
        key: "allowWriteCommands",
        label: "Allow write commands",
        type: "toggle",
        default: true,
        hint: "When off, rm/mv/cp/sed/mkdir/touch are removed from the dev/ci allowlist.",
        meta: { visibleWhen: { key: "shellPolicy", values: ["dev", "ci"] } },
      },
      {
        key: "blockGitPush",
        label: "Block git push",
        type: "toggle",
        default: true,
        hint: "Reject commands that push to remotes. Default on for ci; recommended for dev on shared hosts.",
        meta: { visibleWhen: SHELL_POLICY_VISIBLE_WHEN },
      },
      {
        key: "blockPackagePublish",
        label: "Block package publish",
        type: "toggle",
        default: true,
        hint: "Reject npm/pnpm/yarn publish and unpublish commands.",
        meta: { visibleWhen: SHELL_POLICY_VISIBLE_WHEN },
      },
      {
        key: "blockDestructiveRm",
        label: "Block destructive rm",
        type: "toggle",
        default: true,
        hint: "Reject rm -rf and similar destructive removal patterns.",
        meta: { visibleWhen: SHELL_POLICY_VISIBLE_WHEN },
      },
      {
        key: "blockInlineCodeExecution",
        label: "Block inline code execution",
        type: "toggle",
        default: true,
        hint: "Reject python -c, node -e, bash -c, and similar escape hatches.",
        meta: { visibleWhen: SHELL_POLICY_VISIBLE_WHEN },
      },
      {
        key: "allowShellMetacharacters",
        label: "Allow shell chaining",
        type: "toggle",
        default: false,
        hint: "When enabled, permits ; | & ` $() and redirects. Not recommended on shared hosts.",
        meta: { visibleWhen: SHELL_POLICY_VISIBLE_WHEN },
      },
      {
        key: "allowShellAbsolutePaths",
        label: "Allow absolute paths in shell",
        type: "toggle",
        default: false,
        hint: "When enabled, commands may reference paths outside the workspace (e.g. /etc, ~).",
        meta: { visibleWhen: SHELL_POLICY_VISIBLE_WHEN },
      },
      { key: "shellTimeoutSec", label: "Shell timeout seconds", type: "number", default: 120 },
      { key: "maxShellCommandLength", label: "Max shell command length", type: "number", default: 4096, meta: { visibleWhen: SHELL_POLICY_VISIBLE_WHEN } },
      { key: "timeoutSec", label: "Timeout seconds", type: "number", default: 0 },
      { key: "graceSec", label: "Grace seconds", type: "number", default: 15 },
      { key: "httpReferer", label: "HTTP referer", type: "text", default: "https://paperclip.ing" },
      { key: "openRouterTitle", label: "OpenRouter title", type: "text", default: "Paperclip" },
      { key: "traceName", label: "Trace name", type: "text", default: "Paperclip Direct OpenRouter" },
      { key: "traceEnvironment", label: "Trace environment", type: "text" },
      { key: "env", label: "Environment JSON", type: "textarea" },
    ],
  };
}
